import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          "min-h-screen max-w-2xl mx-auto flex p-4 md:p-8 text-neutral-900"
        }
      >
        {children}
      </body>
    </html>
  );
}
